/*
 * Weather API
 *  # Introduction  WeatherAPI.com provides access to weather and geo data via a JSON/XML restful API. It allows developers to create desktop, web and mobile applications using this data very easy.    We provide following data through our API:     - Real-time weather - 14 day weather forecast - Astronomy - Time zone - Location data - Search or Autocomplete API - NEW: Historical weather - NEW: Future Weather (Upto 300 days ahead) - Weather Alerts - Air Quality Data  # Getting Started    You need to [signup](https://www.weatherapi.com/signup.aspx) and then you can find your API key under [your account](https://www.weatherapi.com/login.aspx), and start using API right away!    We have [code libraries](https://www.weatherapi.com/docs/code-libraries.aspx) for different programming languages like PHP, .net, JAVA, etc.  If you find any features missing or have any suggestions, please [contact us](https://www.weatherapi.com/contact.aspx).    # Authentication    API access to the data is protected by an API key. If at anytime, you find the API key has become vulnerable, please regenerate the key using Regenerate button next to the API key.  Authentication to the WeatherAPI.com API is provided by passing your API key as request parameter through an API .      ##  key parameter  key=<YOUR API KEY>  
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.WeatherApi) {
      root.WeatherApi = {};
    }
    root.WeatherApi.Current = factory(root.WeatherApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The Current model module.
   * @module model/Current
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Current</code>.
   * @alias module:model/Current
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Current</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Current} obj Optional instance to populate.
   * @return {module:model/Current} The populated <code>Current</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('last_updated_epoch'))
        obj.lastUpdatedEpoch = ApiClient.convertToType(data['last_updated_epoch'], 'Number');
      if (data.hasOwnProperty('last_updated'))
        obj.lastUpdated = ApiClient.convertToType(data['last_updated'], 'String');
      if (data.hasOwnProperty('temp_c'))
        obj.tempC = ApiClient.convertToType(data['temp_c'], 'Number');
      if (data.hasOwnProperty('temp_f'))
        obj.tempF = ApiClient.convertToType(data['temp_f'], 'Number');
      if (data.hasOwnProperty('is_day'))
        obj.isDay = ApiClient.convertToType(data['is_day'], 'Number');
      if (data.hasOwnProperty('condition'))
        obj.condition = ApiClient.convertToType(data['condition'], Object);
      if (data.hasOwnProperty('wind_mph'))
        obj.windMph = ApiClient.convertToType(data['wind_mph'], 'Number');
      if (data.hasOwnProperty('wind_kph'))
        obj.windKph = ApiClient.convertToType(data['wind_kph'], 'Number');
      if (data.hasOwnProperty('wind_degree'))
        obj.windDegree = ApiClient.convertToType(data['wind_degree'], 'Number');
      if (data.hasOwnProperty('wind_dir'))
        obj.windDir = ApiClient.convertToType(data['wind_dir'], 'String');
      if (data.hasOwnProperty('pressure_mb'))
        obj.pressureMb = ApiClient.convertToType(data['pressure_mb'], 'Number');
      if (data.hasOwnProperty('pressure_in'))
        obj.pressureIn = ApiClient.convertToType(data['pressure_in'], 'Number');
      if (data.hasOwnProperty('precip_mm'))
        obj.precipMm = ApiClient.convertToType(data['precip_mm'], 'Number');
      if (data.hasOwnProperty('precip_in'))
        obj.precipIn = ApiClient.convertToType(data['precip_in'], 'Number');
      if (data.hasOwnProperty('humidity'))
        obj.humidity = ApiClient.convertToType(data['humidity'], 'Number');
      if (data.hasOwnProperty('cloud'))
        obj.cloud = ApiClient.convertToType(data['cloud'], 'Number');
      if (data.hasOwnProperty('feelslike_c'))
        obj.feelslikeC = ApiClient.convertToType(data['feelslike_c'], 'Number');
      if (data.hasOwnProperty('feelslike_f'))
        obj.feelslikeF = ApiClient.convertToType(data['feelslike_f'], 'Number');
      if (data.hasOwnProperty('vis_km'))
        obj.visKm = ApiClient.convertToType(data['vis_km'], 'Number');
      if (data.hasOwnProperty('vis_miles'))
        obj.visMiles = ApiClient.convertToType(data['vis_miles'], 'Number');
      if (data.hasOwnProperty('uv'))
        obj.uv = ApiClient.convertToType(data['uv'], 'Number');
      if (data.hasOwnProperty('gust_mph'))
        obj.gustMph = ApiClient.convertToType(data['gust_mph'], 'Number');
      if (data.hasOwnProperty('gust_kph'))
        obj.gustKph = ApiClient.convertToType(data['gust_kph'], 'Number');
      if (data.hasOwnProperty('air_quality'))
        obj.airQuality = ApiClient.convertToType(data['air_quality'], Object);
    }
    return obj;
  }

  /**
   * @member {Number} lastUpdatedEpoch
   */
  exports.prototype.lastUpdatedEpoch = undefined;

  /**
   * @member {String} lastUpdated
   */
  exports.prototype.lastUpdated = undefined;

  /**
   * @member {Number} tempC
   */
  exports.prototype.tempC = undefined;

  /**
   * @member {Number} tempF
   */
  exports.prototype.tempF = undefined;

  /**
   * @member {Number} isDay
   */
  exports.prototype.isDay = undefined;

  /**
   * @member {Object} condition
   */
  exports.prototype.condition = undefined;

  /**
   * @member {Number} windMph
   */
  exports.prototype.windMph = undefined;

  /**
   * @member {Number} windKph
   */
  exports.prototype.windKph = undefined;

  /**
   * @member {Number} windDegree
   */
  exports.prototype.windDegree = undefined;

  /**
   * @member {String} windDir
   */
  exports.prototype.windDir = undefined;

  /**
   * @member {Number} pressureMb
   */
  exports.prototype.pressureMb = undefined;

  /**
   * @member {Number} pressureIn
   */
  exports.prototype.pressureIn = undefined;

  /**
   * @member {Number} precipMm
   */
  exports.prototype.precipMm = undefined;

  /**
   * @member {Number} precipIn
   */
  exports.prototype.precipIn = undefined;

  /**
   * @member {Number} humidity
   */
  exports.prototype.humidity = undefined;

  /**
   * @member {Number} cloud
   */
  exports.prototype.cloud = undefined;

  /**
   * @member {Number} feelslikeC
   */
  exports.prototype.feelslikeC = undefined;

  /**
   * @member {Number} feelslikeF
   */
  exports.prototype.feelslikeF = undefined;

  /**
   * @member {Number} visKm
   */
  exports.prototype.visKm = undefined;

  /**
   * @member {Number} visMiles
   */
  exports.prototype.visMiles = undefined;

  /**
   * @member {Number} uv
   */
  exports.prototype.uv = undefined;

  /**
   * @member {Number} gustMph
   */
  exports.prototype.gustMph = undefined;

  /**
   * @member {Number} gustKph
   */
  exports.prototype.gustKph = undefined;

  /**
   * @member {Object} airQuality
   */
  exports.prototype.airQuality = undefined;


  return exports;

}));
